### ISSUE TITLE
error "Could not resolve call to operator SameAs with signature (FHIR.dateTime,System.DateTime)"

### ISSUE THREAD

**Issue by JozefAerts** [cqframework/cql-execution#117]
I am just starting with CQL, so I presume I am just doing something wrong ...
I tried to run numerous of the examples, but usually was drowned in error messages.
So I tried with some very extremely simple examples, but also there, I soon get errors...
My java command e.g. is:
set CLASSPATH="..\jar_files_downloaded\*"
java -cp %CLASSPATH% org.cqframework.cql.cql2elm.CqlTranslator -input C:\HL7_CQL\cqframework_software\clinical_quality_language-master\clinical_quality_language-master\Examples\EH_CMS9v4_NQF0480_BF_ExclusiveBreastFeed\test_jozef.cql

My CQL is:
library CMS9v4_CDS version '1'

using FHIR version '1.4'

/* valueset definitions */
valueset "Feeding Intention-Breast": '2.16.840.1.113762.1.4.1045.29'
valueset "Feeding Intention-Not-To-Breast": 'TBD' // Code '636111000124114' from "SNOMED-CT" display: 'Mother refuses to breastfeed (situation)'
valueset "Galactosemia": '2.16.840.1.113883.3.117.1.7.1.35'
valueset "Single Live Birth": '2.16.840.1.113883.3.117.1.7.1.25'
valueset "Single Live Born Newborn Born in Hospital": '2.16.840.1.113883.3.117.1.7.1.26'
valueset "Encounter Inpatient": '2.16.840.1.113883.3.666.5.307'
valueset "Estimated Gestational Age at Birth": '2.16.840.1.113762.1.4.1045.47'
valueset "Parenteral Nutrition": '2.16.840.1.113883.3.117.1.7.1.38'
valueset "Breast Milk": '2.16.840.1.113883.3.117.1.7.1.30'
valueset "Dietary Intake Other than Breast Milk": '2.16.840.1.113883.3.117.1.7.1.27'
valueset "Neonatal Intensive Care Unit (NICU)": '2.16.840.1.113883.3.117.1.7.1.75'
valueset "Patient Expired": '2.16.840.1.113883.3.117.1.7.1.309'
valueset "Discharge To Acute Care Facility": '2.16.840.1.113883.3.117.1.7.1.87'

/* check for breastfeeding - exclusions */
	
/* further definitions */
/* Breastfeeding Exclusion */
/* define "Breastfeeding Exclusions": [Condition: "Galactosemia"] */
/* Breastfeeding intention */

/* Testing */
define "Breastfeeding Exclusions":
  [Condition: "Galactosemia"]

define "Intention to Breastfeed":
  [RiskAssessment: "Feeding Intention-Breast"] R
    where R.date 1 hour or more after "Infant Birth Date"
	
define "Breastfeeding Intention":
  "Intention to Breastfeed"
    /* union "Intention not to Breastfeed" */

// the following definition contains errors
/* define "Intention not to Breastfeed":
  [RiskAssessment: "Feeding Intention-Not-To-Breastfeed"] R
    where R.date 1 hour or more after "Infant Birth Date" 
*/
	
/** taken from file CMS9v4_CQM-cql */
define "Infant Birth Date":
  Last("Single Live Birth Condition").abatementDateTime.value
  
/** taken from file CMS9v4_CQM-cql */
define "Single Live Birth Condition":
  ([Condition: "Single Live Birth"]
    union [Condition: "Single Live Born Newborn Born in Hospital"]) Condition
    where Condition.clinicalStatus.value = 'active'
      and Condition.verificationStatus.value = 'confirmed'

When I run this with the above Java command, I get: 
Translation failed due to errors:
Warning:[31:3, 31:29] Could not resolve membership operator for terminology target of the retrieve.
Warning:[34:3, 34:46] Could not resolve membership operator for terminology target of the retrieve.
Warning:[54:4, 54:35] Could not resolve membership operator for terminology target of the retrieve.
Warning:[55:11, 55:66] Could not resolve membership operator for terminology target of the retrieve.
Error:[35:18, 35:37] Could not resolve call to operator SameOrAfter with signature (FHIR.dateTime,System.DateTime).

2 questions:
- what do the warnings mean? I could not find any documentation
- according to the specification, "dateTime" is supported by "SameOrAfter", so I do not understand why I get the error.
My apologies if this is not the place for posting this, but I could not find any "beginners forum" anywhere. If there is such one, I will be happy to repost there.

**Comment by cmoesel** [comment]
I apologize as I somehow missed seeing this issue long ago.  You're probably way past this now, but:
* The warnings are likely due to the FHIR modelinfo missing the default `codeProperty` definition for one of the resource types you are retrieving.  In all likelihood, this is fixed in more recent versions of the CQL-to-ELM translator (and its bundled FHIR modelinfo files)
* The error is because you are trying to compare some _FHIR_ `dateTime` values (which are complex datatypes supporting extensions) with CQL system `DateTime` values (which are simple datatypes).  This is likely arising from one of the spots where you compare `R.date` (FHIR `datetime`) to `"Infant Birth Date"` (CQL `DateTime`).  The fix is fairly simple; just change `date` to `date.value` in the CQL.

**Comment by cmoesel** [comment]
Closing as answered.
