### ISSUE TITLE
Need help and few clarification during execution of CMS68v9 measure 

### ISSUE THREAD

**Issue by shardulbanker** [cqframework/cql-execution#132]
I have converted 2020 year measure-CMS68v9 CQL to coffee script. I am learning to create coffee script file for the execution for same measure. I have created exec-68v9.coffee script as under. I have performed cake build and when I try to execute it gives no result. 
Following are the contents of required file.
68v9.coffee
---------------------------------------------------------------------------------------------------------
module.exports = {
   "library" : {
      "annotation" : [ {
         "translatorOptions" : "",
         "type" : "CqlToElmInfo"
      } ],
      "identifier" : {
         "id" : "DocumentationofCurrentMedicationsintheMedicalRecord",
         "version" : "9.1.000"
      },
      "schemaIdentifier" : {
         "id" : "urn:hl7-org:elm",
         "version" : "r1"
      },
      "usings" : {
         "def" : [ {
            "localIdentifier" : "System",
            "uri" : "urn:hl7-org:elm-types:r1"
         }, {
            "localIdentifier" : "QDM",
            "uri" : "urn:healthit-gov:qdm:v5_4",
            "version" : "5.4"
         } ]
      },
      "parameters" : {
         "def" : [ {
            "name" : "Measurement Period",
            "accessLevel" : "Public",
            "parameterTypeSpecifier" : {
               "type" : "IntervalTypeSpecifier",
               "pointType" : {
                  "name" : "{urn:hl7-org:elm-types:r1}DateTime",
                  "type" : "NamedTypeSpecifier"
               }
            }
         } ]
      },
      "codeSystems" : {
         "def" : [ {
            "name" : "LOINC",
            "id" : "urn:oid:2.16.840.1.113883.6.1",
            "accessLevel" : "Public"
         }, {
            "name" : "SNOMEDCT",
            "id" : "urn:oid:2.16.840.1.113883.6.96",
            "accessLevel" : "Public"
         } ]
      },
      "valueSets" : {
         "def" : [ {
            "name" : "Ethnicity",
            "id" : "urn:oid:2.16.840.1.114222.4.11.837",
            "accessLevel" : "Public"
         }, {
            "name" : "Medical or Other reason not done",
            "id" : "urn:oid:2.16.840.1.113883.3.600.1.1502",
            "accessLevel" : "Public"
         }, {
            "name" : "Medications Encounter Code Set",
            "id" : "urn:oid:2.16.840.1.113883.3.600.1.1834",
            "accessLevel" : "Public"
         }, {
            "name" : "ONC Administrative Sex",
            "id" : "urn:oid:2.16.840.1.113762.1.4.1",
            "accessLevel" : "Public"
         }, {
            "name" : "Payer",
            "id" : "urn:oid:2.16.840.1.114222.4.11.3591",
            "accessLevel" : "Public"
         }, {
            "name" : "Race",
            "id" : "urn:oid:2.16.840.1.114222.4.11.836",
            "accessLevel" : "Public"
         } ]
      },
      "codes" : {
         "def" : [ {
            "name" : "Birth date",
            "id" : "21112-8",
            "display" : "Birth date",
            "accessLevel" : "Public",
            "codeSystem" : {
               "name" : "LOINC"
            }
         }, {
            "name" : "Documentation of current medications (procedure)",
            "id" : "428191000124101",
            "display" : "Documentation of current medications (procedure)",
            "accessLevel" : "Public",
            "codeSystem" : {
               "name" : "SNOMEDCT"
            }
         } ]
      },
      "statements" : {
         "def" : [ {
            "name" : "Patient",
            "context" : "Patient",
            "expression" : {
               "type" : "SingletonFrom",
               "operand" : {
                  "dataType" : "{urn:healthit-gov:qdm:v5_4}Patient",
                  "templateId" : "Patient",
                  "type" : "Retrieve"
               }
            }
         }, {
            "name" : "SDE Ethnicity",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "dataType" : "{urn:healthit-gov:qdm:v5_4}PatientCharacteristicEthnicity",
               "codeProperty" : "code",
               "type" : "Retrieve",
               "codes" : {
                  "name" : "Ethnicity",
                  "type" : "ValueSetRef"
               }
            }
         }, {
            "name" : "SDE Payer",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "dataType" : "{urn:healthit-gov:qdm:v5_4}PatientCharacteristicPayer",
               "codeProperty" : "code",
               "type" : "Retrieve",
               "codes" : {
                  "name" : "Payer",
                  "type" : "ValueSetRef"
               }
            }
         }, {
            "name" : "SDE Race",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "dataType" : "{urn:healthit-gov:qdm:v5_4}PatientCharacteristicRace",
               "codeProperty" : "code",
               "type" : "Retrieve",
               "codes" : {
                  "name" : "Race",
                  "type" : "ValueSetRef"
               }
            }
         }, {
            "name" : "SDE Sex",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "dataType" : "{urn:healthit-gov:qdm:v5_4}PatientCharacteristicSex",
               "codeProperty" : "code",
               "type" : "Retrieve",
               "codes" : {
                  "name" : "ONC Administrative Sex",
                  "type" : "ValueSetRef"
               }
            }
         }, {
            "name" : "Qualifying Encounters During Measurement Period",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "type" : "Query",
               "source" : [ {
                  "alias" : "QualifyingEncounter",
                  "expression" : {
                     "dataType" : "{urn:healthit-gov:qdm:v5_4}PositiveEncounterPerformed",
                     "templateId" : "PositiveEncounterPerformed",
                     "codeProperty" : "code",
                     "type" : "Retrieve",
                     "codes" : {
                        "name" : "Medications Encounter Code Set",
                        "type" : "ValueSetRef"
                     }
                  }
               } ],
               "relationship" : [ ],
               "where" : {
                  "type" : "IncludedIn",
                  "operand" : [ {
                     "path" : "relevantPeriod",
                     "scope" : "QualifyingEncounter",
                     "type" : "Property"
                  }, {
                     "name" : "Measurement Period",
                     "type" : "ParameterRef"
                  } ]
               }
            }
         }, {
            "name" : "CalendarAgeInYearsAt",
            "context" : "Patient",
            "accessLevel" : "Public",
            "type" : "FunctionDef",
            "expression" : {
               "precision" : "Year",
               "type" : "DurationBetween",
               "operand" : [ {
                  "type" : "ToDate",
                  "operand" : {
                     "name" : "BirthDateTime",
                     "type" : "OperandRef"
                  }
               }, {
                  "type" : "ToDate",
                  "operand" : {
                     "name" : "AsOf",
                     "type" : "OperandRef"
                  }
               } ]
            },
            "operand" : [ {
               "name" : "BirthDateTime",
               "operandTypeSpecifier" : {
                  "name" : "{urn:hl7-org:elm-types:r1}DateTime",
                  "type" : "NamedTypeSpecifier"
               }
            }, {
               "name" : "AsOf",
               "operandTypeSpecifier" : {
                  "name" : "{urn:hl7-org:elm-types:r1}DateTime",
                  "type" : "NamedTypeSpecifier"
               }
            } ]
         }, {
            "name" : "Patient Age 18 or Older at Start of Measurement Period",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "type" : "Exists",
               "operand" : {
                  "type" : "Query",
                  "source" : [ {
                     "alias" : "BirthDate",
                     "expression" : {
                        "dataType" : "{urn:healthit-gov:qdm:v5_4}PatientCharacteristicBirthdate",
                        "codeProperty" : "code",
                        "type" : "Retrieve",
                        "codes" : {
                           "type" : "ToList",
                           "operand" : {
                              "name" : "Birth date",
                              "type" : "CodeRef"
                           }
                        }
                     }
                  } ],
                  "relationship" : [ ],
                  "where" : {
                     "type" : "GreaterOrEqual",
                     "operand" : [ {
                        "name" : "CalendarAgeInYearsAt",
                        "type" : "FunctionRef",
                        "operand" : [ {
                           "path" : "birthDatetime",
                           "scope" : "BirthDate",
                           "type" : "Property"
                        }, {
                           "type" : "Start",
                           "operand" : {
                              "name" : "Measurement Period",
                              "type" : "ParameterRef"
                           }
                        } ]
                     }, {
                        "valueType" : "{urn:hl7-org:elm-types:r1}Integer",
                        "value" : "18",
                        "type" : "Literal"
                     } ]
                  }
               }
            }
         }, {
            "name" : "Initial Population",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "type" : "Query",
               "source" : [ {
                  "alias" : "QualifyingEncounter",
                  "expression" : {
                     "name" : "Qualifying Encounters During Measurement Period",
                     "type" : "ExpressionRef"
                  }
               } ],
               "relationship" : [ ],
               "where" : {
                  "name" : "Patient Age 18 or Older at Start of Measurement Period",
                  "type" : "ExpressionRef"
               }
            }
         }, {
            "name" : "Denominator",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "name" : "Initial Population",
               "type" : "ExpressionRef"
            }
         }, {
            "name" : "Medications Not Documented for Medical Reason",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "type" : "Query",
               "source" : [ {
                  "alias" : "NotPerformed",
                  "expression" : {
                     "dataType" : "{urn:healthit-gov:qdm:v5_4}NegativeProcedurePerformed",
                     "templateId" : "NegativeProcedurePerformed",
                     "codeProperty" : "code",
                     "type" : "Retrieve",
                     "codes" : {
                        "type" : "ToList",
                        "operand" : {
                           "name" : "Documentation of current medications (procedure)",
                           "type" : "CodeRef"
                        }
                     }
                  }
               } ],
               "relationship" : [ ],
               "where" : {
                  "type" : "InValueSet",
                  "code" : {
                     "path" : "negationRationale",
                     "scope" : "NotPerformed",
                     "type" : "Property"
                  },
                  "valueset" : {
                     "name" : "Medical or Other reason not done"
                  }
               }
            }
         }, {
            "name" : "Denominator Exceptions",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "type" : "Query",
               "source" : [ {
                  "alias" : "EncounterDuringMeasurementPeriod",
                  "expression" : {
                     "name" : "Qualifying Encounters During Measurement Period",
                     "type" : "ExpressionRef"
                  }
               } ],
               "relationship" : [ {
                  "alias" : "MedicationsNotDocumented",
                  "type" : "With",
                  "expression" : {
                     "name" : "Medications Not Documented for Medical Reason",
                     "type" : "ExpressionRef"
                  },
                  "suchThat" : {
                     "type" : "In",
                     "operand" : [ {
                        "path" : "authorDatetime",
                        "scope" : "MedicationsNotDocumented",
                        "type" : "Property"
                     }, {
                        "path" : "relevantPeriod",
                        "scope" : "EncounterDuringMeasurementPeriod",
                        "type" : "Property"
                     } ]
                  }
               } ]
            }
         }, {
            "name" : "Medications Documented During Qualifying Encounter",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "type" : "Query",
               "source" : [ {
                  "alias" : "QualifyingEncounterDuringMeasurementPeriod",
                  "expression" : {
                     "name" : "Qualifying Encounters During Measurement Period",
                     "type" : "ExpressionRef"
                  }
               } ],
               "relationship" : [ {
                  "alias" : "MedicationsDocumented",
                  "type" : "With",
                  "expression" : {
                     "dataType" : "{urn:healthit-gov:qdm:v5_4}PositiveProcedurePerformed",
                     "templateId" : "PositiveProcedurePerformed",
                     "codeProperty" : "code",
                     "type" : "Retrieve",
                     "codes" : {
                        "type" : "ToList",
                        "operand" : {
                           "name" : "Documentation of current medications (procedure)",
                           "type" : "CodeRef"
                        }
                     }
                  },
                  "suchThat" : {
                     "type" : "IncludedIn",
                     "operand" : [ {
                        "path" : "relevantPeriod",
                        "scope" : "MedicationsDocumented",
                        "type" : "Property"
                     }, {
                        "path" : "relevantPeriod",
                        "scope" : "QualifyingEncounterDuringMeasurementPeriod",
                        "type" : "Property"
                     } ]
                  }
               } ]
            }
         }, {
            "name" : "Numerator",
            "context" : "Patient",
            "accessLevel" : "Public",
            "expression" : {
               "name" : "Medications Documented During Qualifying Encounter",
               "type" : "ExpressionRef"
            }
         } ]
      }
   }
}
---------------------------------------------------------------------------------------------------------

 exec-68v9.coffee
---------------------------------------------------------------------------------------------------------
cql = require '../cql'
codes = require '../cql-code-service'
measure = require './68v9'

cservice = new codes.CodeService {
    "1.2.3.4.5": {
      "1": [
        {
          "code": "ABC",
          "system": "5.4.3.2.1",
          "version": "1"
        }, {
          "code": "DEF",
          "system": "5.4.3.2.1",
          "version": "2"
        }, {
          "code": "GHI",
          "system": "5.4.3.4.5",
          "version": "3"
        }
      ],
      "2": [
        {
          "code": "ABC",
          "system": "5.4.3.2.1",
          "version": "1"
        }, {
          "code": "DEF",
          "system": "5.4.3.2.1",
          "version": "2"
        }, {
          "code": "JKL",
          "system": "5.4.3.2.1",
          "version": "3"
        }
      ]
    },
    "6.7.8.9.0": {
      "A": [
        {
          "code": "MNO",
          "system": "2.4.6.8.0",
          "version": "3"
        }, {
          "code": "PQR",
          "system": "2.4.6.8.0",
          "version": "2"
        }, {
          "code": "STU",
          "system": "2.4.6.8.0",
          "version": "1"
        }
      ]
    }
  }

lib = new cql.Library(measure)
parameters = {
  MeasurementPeriod: new cql.Interval(cql.DateTime.parse('2019-01-01'), cql.DateTime.parse('2020-01-01'), true, false)
}
executor = new cql.Executor(lib, cservice, parameters)
psource = new cql.PatientSource [ {
    "resourceType": "Bundle",
    "id": "example1",
    "meta": {
      "versionId": "1",
      "lastUpdated": "2014-08-18T01:43:30Z"
    },
    "base": "http://example.com/base",
    "entry" : [{
        "resource": {
        "id" : "1",
        "meta" :{ "profile" : ["patient-qicore-qicore-patient"]},
        "resourceType" : "Patient",
        "identifier": [{ "value": "1" }],
        "name": {"given":["John"], "family": ["Smith"]},
        "gender": "M",
        "birthDate" : "1980-02-17T06:15"}
        }
    ]
  }, {
    "resourceType": "Bundle",
    "id": "example1",
    "meta": {
      "versionId": "1",
      "lastUpdated": "2014-08-18T01:43:30Z"
    },
    "base": "http://example.com/base",
    "entry" : [{
        "resource": {
        "id" : "2",
        "meta" :{ "profile" : ["patient-qicore-qicore-patient"]},
        "resourceType" : "Patient",
        "identifier": [{ "value": "2" }],
        "name": {"given":["Sally"], "family": ["Smith"]},
        "gender": "F",
        "birthDate" : "2007-08-02T11:47"}
        }
    ]
  } ]

result = executor.exec(psource)
console.log JSON.stringify(result, undefined, 2)
---------------------------------------------------------------------------------------------------------

When I perform execution of exec-68v9.coffee script, It gives no result. Everything is empty. I am not able to understand this. Please help to understand. 
I have following questions.
1) How can I give value sets using code service in exec file?  Please share existing Ethnicity/Medications Encounter Code Set/Race or similar value sets to put as part of code service.
2) How can I give SNOWMED data as patient source? In future How can I give required patient's data in JSON format? Please share any sample JSON format.

I am stuck and not able to proceed further. Please help to answer questions or any kind of help will be really appreciated.

Thanks.

**Comment by shardulbanker** [comment]
In continue to above issue, I am getting below result when I perform "node exec-68v9.coffee" execution.

node exec-68v9
{
  "patientResults": {
    "1": {
      "Patient": null,
      "SDE Ethnicity": [],
      "SDE Payer": [],
      "SDE Race": [],
      "SDE Sex": [],
      "Qualifying Encounters During Measurement Period": [],
      "Patient Age 18 or Older at Start of Measurement Period": false,
      "Initial Population": [],
      "Denominator": [],
      "Medications Not Documented for Medical Reason": [],
      "Denominator Exceptions": [],
      "Medications Documented During Qualifying Encounter": [],
      "Numerator": []
    },
    "2": {
      "Patient": null,
      "SDE Ethnicity": [],
      "SDE Payer": [],
      "SDE Race": [],
      "SDE Sex": [],
      "Qualifying Encounters During Measurement Period": [],
      "Patient Age 18 or Older at Start of Measurement Period": false,
      "Initial Population": [],
      "Denominator": [],
      "Medications Not Documented for Medical Reason": [],
      "Denominator Exceptions": [],
      "Medications Documented During Qualifying Encounter": [],
      "Numerator": []
    }
  },
  "unfilteredResults": {},
  "localIdPatientResultsMap": {
    "1": {
      "DocumentationofCurrentMedicationsintheMedicalRecord": {}
    },
    "2": {
      "DocumentationofCurrentMedicationsintheMedicalRecord": {}
    }
  }
}

I am getting empty results in accordance with all setup done as per earlier comment.

**Comment by cmoesel** [comment]
Hi @shardulbanker.  As I noted in #131, the `cql-execution` library alone is not sufficient for executing measures.  This is especially true of QDM-based measures.  The `cql-execution` library does not know anything about QDM -- so you need to provide a QDM-aware `PatientSource` that knows how to query and return patient data in a QDM-compatible format.  As for the code service, you need to provide a code service that knows how to resolve the value set OIDs or URLs to a set of codes using a terminology service.  The `cql-execution` library does not provide any of this -- it is focused on handling CQL logical operations, and requires other libraries to handle data and value set queries.

As noted in #131, you probably want to try using [cqm-execution](https://github.com/projecttacoma/cqm-execution), which is based on `cql-execution` but provides support for QDM-based eCQMs.

**Comment by shardulbanker** [comment]
Thanks for an update. I will try as suggested and let you know if any questions.

**Comment by cmoesel** [comment]
Closing as "answered".
