### ISSUE TITLE
LastPositionOf function is not implemented

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/cql-execution#147]
It appears the LastPositionOf function is not implemented:

https://github.com/cqframework/cql-execution/blob/master/src/elm/string.coffee#L69

**Comment by cmoesel** [comment]
Thanks, Bryn.  This should be easy enough to fix, but we'll likely do it in the 2.0.0 beta branch (which is straight JS rather than coffee).  Would that work for you?

**Comment by brynrhodes** [comment]
Yes, totally fine, we worked around it for our use case by rewriting the logic to avoid the use of the LastPositionOf function.
