### ISSUE TITLE
unable to implement string comparison

### ISSUE THREAD

**Issue by arby50** [cqframework/cql-execution#149]
I have created a simple test case to check for the patient gender = 'female' using the following cql:
```
library MyTest version '1'
using FHIR version '4.0.1'
include FHIRHelpers version '4.0.1' called FHIRHelpers

context Patient

define "Is Female":
  Patient.gender in 'female'
  
define "Is Female2":
  Patient.gender = 'female'
  
define "Is Female3":
  Patient.gender.value = 'female'

```
Using the resulting elm/json, as well as several patients, the results are always null.  I have tried the current cql-execution as well as the V2 beta.  The problem seems to be in the method: 
`function getPropertyFromObject(obj, path)`
in \src\elm\structured.js

The 'obj' passed in is the actual string 'female', the 'path' is a string: 'value'.  Since the string 'female' is not an object, the property called 'value' is not found so a null is returned.  Since gender is actually a 'code' and not a string according to FHIR, I tried using gender.value above but got the same result.

I can confirm the librarys are getting loaded properly and the Patient is loaded properly as well.

**Comment by cmoesel** [comment]
Hi @arby50.  I've definitely used logic like this successfully in the past.  I would expect it to work.  Are you using the [cql-exec-fhir](https://github.com/cqframework/cql-exec-fhir) `PatientSource`?

**Comment by arby50** [comment]
no, but I will take a look and report back.  Thanks for the prompt reply, much obliged!

**Comment by cmoesel** [comment]
Ah, yes, you'll definitely need to use the `cql-exec-fhir` module if you want to execute any CQL using the FHIR data model. Another important thing to note is that you need to supply a `CodeService` that knows how to resolve value sets and check for code membership in them.  There is an open source [cql-exec-vsac](https://github.com/cqframework/cql-exec-vsac) module if you uses value sets from the National Library of Medicine's Value Set Authority Center.  If you use value sets from a different source, however, you will need to provide your own `CodeService` implementation or load value set contents into the standard `CodeService` in `cql-execution`.

The [cql-exec-examples](https://github.com/cqframework/cql-exec-examples) repo contains working code that shows how to use `cql-execution` with `cql-exec-fhir` and `cql-exec-vsac`.

**Comment by arby50** [comment]
That was the problem.  When using the `cql-exec-fhir` module, the 'obj', was now a FhirObject and the string was found.  I had some trouble finding the Patient as my json/ELM added a templateId:
`"templateId" : "http://hl7.org/fhir/StructureDefinition/Patient",`
once I removed that line, Patient was found as was patient.gender.
Thanks again, very helpful and impressively prompt response(s)!

**Comment by cmoesel** [comment]
And thank _you_ for providing an update!
