### ISSUE TITLE
Error raised because FHIR Helpers Library not in ctx

### ISSUE THREAD

**Issue by TylerNoblett** [cqframework/cql-execution#154]
#### Description
Hi! First off, thanks for all of your work on this repo - I really appreciate it, especially porting it from coffeescript to JS!

I'm using V2 (the JS version of cql-execution) along with cql-exec-fhir to execute the JSON-ELM produced version of [this](https://github.com/cqframework/CQL-Formatting-and-Usage-Wiki/blob/3fe9f16d75993f5a21045a7eb1000c93a4a56ede/Source/Cooking%20With%20CQL/41/126_BloodPressureComponents.cql) CQL file, but when running the exec JS file, I get the following error:
```
.../cql-execution/src/elm/reusable.js:66
    functionDefs = functionDefs.filter(f => f.parameters.length === args.length);
                                ^
TypeError: Cannot read property 'filter' of undefined
```
This error occurs in `src/elm/reusable.js`. When debugging, I found that `this.Library` is "FHIRHelpers" and `lib` returns undefined. The `ctx` object's attributes are all undefined, or are empty arrays or objects (see the entire `ctx` object [here](https://controlc.com/17487cfb)), except for `context_values`, which you can view [here](https://pastebin.com/8gQbMhtz), and `parent`, which you can view [here](https://controlc.com/c206958d). I've also included a branch that has all of the necessary files to reproduce this issue (see below in the "To Reproduce" section) and have had a teammate confirm he is getting the same error.

```javascript
class FunctionRef extends Expression {
  constructor(json) {
    super(json);
    this.name = json.name;
    this.library = json.libraryName;
  }
  exec(ctx) {
    let functionDefs, child_ctx;
    if (this.library) {
      const lib = ctx.get(this.library);
      functionDefs = lib ? lib.getFunction(this.name) : undefined;
      const libCtx = ctx.getLibraryContext(this.library);
      child_ctx = libCtx ? libCtx.childContext() : undefined;
    } else {
      functionDefs = ctx.get(this.name);
      child_ctx = ctx.childContext();
    }
    const args = this.execArgs(ctx);

    // Filter out functions w/ wrong number of arguments.
    functionDefs = functionDefs.filter(f => f.parameters.length === args.length);
...
```
The error seems to occur any time that an attribute of `BloodPressure` is referenced -  `where BloodPressure.status in {'final', 'amended'}` is the first line in which this occurs, but subsequent lines referencing other `BloodPressure` attributes also cause this error. 

Interestingly enough, when checking to see if an attribute exists (i.e. `where exists(BloodPressure.status)`), no error occurs, and I'm guessing this is because a FHIR helper isn't needed to convert the attribute, since we're just checking to see if it exists.

Additionally, there's a strong chance this could be user error - I am new to FHIR and haven't personally dealt yet with LOINC codes until this point, and there could be something incorrect in my patient data as well (though I replaced my patient data with [this](https://github.com/DBCG/connectathon/blob/4be117b59939bb204711fea2018534ce0cb58c71/fhir3/bundles/measure/EXM165_FHIR3-8.5.000/EXM165_FHIR3-8.5.000-files/tests-numer-EXM165_FHIR3-bundle.json) and got the same error).

#### Screenshots
<img width="1680" alt="Screen Shot 2020-12-16 at 3 57 50 PM" src="https://user-images.githubusercontent.com/22867407/102405651-7b972480-3fb7-11eb-8592-f7d8997815f6.png">

#### To Reproduce
Clone my [fork](https://github.com/amida-tech/cql-execution) of cql-execution
Check out branch `fhir-helpers-issue`, then:
run`yarn`
`cd exec-files`
`node exec-test.js`

**Comment by cmoesel** [comment]
Hi @TylerNoblett.  Thanks for submitting the issue w/ such easy steps to reproduce.  The problem here is that `cql-execution` is trying to load the `FHIRHelpers` library, but cannot find it.  Unfortunately, the error message does not make that very clear.

To solve this, you need to provide the ELM JSON for `FHIRHelpers` and then include it as a dependency when you execute the CQL.  You can download the FHIRHelpers 4.0.0 ELM JSON here:
* https://raw.githubusercontent.com/cqframework/cql-exec-examples/master/fhir-helpers/r4/FHIRHelpers.json

I did this and added it to your `json-elm` folder.  Then I added this `require` statement at the top:
```js
const fhirhelpers = require('../json-elm/FHIRHelpers.json');
```
and modified the bit that creates the `lib` to look like this:
```js
const includedLibs = {
  FHIRHelpers: fhirhelpers
};
const lib = new cql.Library(measure, new cql.Repository(includedLibs));
```

Once I did that, I was able to execute the CQL without any crashing.

**Comment by TylerNoblett** [comment]
ah thank you so much for your speedy reply! I'll give that a try

**Comment by TylerNoblett** [comment]
Was able to successfully reproduce - thanks again!
