### ISSUE TITLE
Issue with date contains with Null Interval

### ISSUE THREAD

**Issue by adongare** [cqframework/cql-execution#223]
Hello,

Bonnie received a ticket where user is trying to test if a date falls in an interval. In this particular case interval has both start and end date null. 
Example cql `@2012-12-03T8:00 in  [null, null]` which returns `true` 

When I looked into the execution-engine, I noticed that [contains](https://github.com/cqframework/cql-execution/blob/47b5f12130717aeb09658c8e24754a7763a87066/src/datatypes/interval.js#L66) function in this scenario is designed to return true. 
From `Interval.contains` function:
```
if (this.lowClosed && this.low == null) {
   lowFn = () => true;
}
if (this.highClosed && this.high == null) {
   highFn = () => true;
}

return ThreeValuedLogic.and(
   lowFn(this.low, item, precision),
   highFn(this.high, item, precision)
)
```
Can someone please confirm if this a bug or I'm misinterpreting it.

Thanks!

**Comment by cmoesel** [comment]
According to the CQL specification, `@2012-12-03T8:00 in [null, null]` is in fact `true` because both boundaries are closed and null.

From https://cql.hl7.org/02-authorsguide.html#operating-on-intervals (**emphasis** mine):
> The starting and ending point of an interval may be `null`, the meaning of which depends on whether the interval is closed (inclusive) or open (exclusive). If a boundary point is `null` and the boundary is exclusive, the boundary is considered unknown and operations involving that point will return `null`. For example:
> ```
> Interval[3, null) contains 5
> ```
> This expression results in `null`. However, **if the point is `null` and the interval boundary is inclusive, the boundary is interpreted as the beginning or ending of the range of the point type.** For example:
> ```
> Interval[3, null] contains 5
> ```
> **This expression returns `true`** because the `null` ending boundary is inclusive and is therefore interpreted as **extending to the end of the range of possible values for the point type of the interval.**

So... if `cql-execution` returns `true` for `@2012-12-03T8:00 in [null, null]`, then it is acting according to spec.

**Comment by adongare** [comment]
Thanks @cmoesel! That makes sense.  
I should have checked CQL specs before opening this ticket. I'll close this ticket.
