### ISSUE TITLE
Port to TypeScript?

### ISSUE THREAD

**Issue by dwwinters** [cqframework/cql-execution#236]
I was really happy to see #47 get closed out.  Is there anyone out there looking to port this library to TypeScript?

**Comment by cmoesel** [comment]
We're taking it one step at a time.  I really like TypeScript, but there are real gaps and limitations (in regard to implementation of the spec) that I think we need to invest in first before investing in porting this to TypeScript.  Unless someone else steps in and does it, I expect we won't see a TypeScript implementation for a little while.

Are you asking this from the point of view of someone wanting to work on the library itself, or someone wanting to consume the library?  If the latter, it's likely feasible that we could publish some `.d.ts` files that provide type definitions for the few outward-facing API points in the library (the executor, patient source, code service, etc).

**Comment by hossenlopp** [comment]
We defined a few TypeScript definitions for the cql-execution outward API for our fqm-execution library. These could possibly be used as a starting point for the inclusion of types in the library.

https://github.com/projecttacoma/fqm-execution/blob/master/src/types/CQLExecution.d.ts
https://github.com/projecttacoma/fqm-execution/blob/master/src/types/CQLTypes.ts

**Comment by dwwinters** [comment]
@cmoesel it's really more of the latter for me.  Thanks @hossenlopp !  That should be a big help if I end up needing the types for a project I'm working on.

**Comment by mgramigna** [comment]
@dwwinters Just to chime in with an update here, our team is planning on porting `cql-execution` to TypeScript, along with some other features, for a v3.0 release. No specific timeline here, and the changes may be incremental (we're going to start by just using `any` for things and setup the proper TS infrastructure before moving on to stricter typing).

But it's coming!
