### ISSUE TITLE
Time values should be unspecified when converting Date using ToDateTime

### ISSUE THREAD

**Issue by dczulada** [cqframework/cql-execution#261]
There could be a bug in the cql-execution (https://github.com/cqframework/cql-execution/blob/b0f53070cdace518adc307ed5ec7afe0086883c3/src/datatypes/datetime.js#L692).  This stems from an inconsistency in the cql-spec.  Bryn has commented on it in the following JIRA ticket (https://oncprojectracking.healthit.gov/support/browse/CQLIT-300).  Looks like the time values should be unspecified instead of 0 when performing ToDateTime on a Date.

**Comment by cmoesel** [comment]
See also: https://jira.hl7.org/browse/FHIR-35869

**Comment by lwisham** [comment]
Can you please confirm if this similar to ticket 263, which was resolved in version 2.4.1?

**Comment by cmoesel** [comment]
Yes, this was fixed.  Thanks for noticing that we left this issue open.  I'm closing it now!
