### ISSUE TITLE
Need help: Trying to resolve the error TS_NODE_PROJECT' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by siisk** [cqframework/cql-execution#302]

**Comment by cmoesel** [comment]
I'm glad you found a solution, @siisk. There is actually an active pull request up that already has [this fix and other Windows-related fixes](https://github.com/cqframework/cql-execution/pull/278/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) in it.  Once it gets merged, the project should work on Windows without needing further edits.
