### ISSUE TITLE
`Implies` operator in CMS144

### ISSUE THREAD

**Issue by birick1** [cqframework/cql-execution#319]
There is an outstanding ticket for implementing the `implies` operator in the engine at #158.

I don't think any measure previously has used the operator.  That changed recently with the measure CMS144 now looking to use the `implies` operator.

In addition, the ELM translator did not support translation of `implies` when #158 was created, but it does now.  Attaching CMS144 and test cases for use in implementing the `implies` feature.
[CMS144FHIR-v1.3.000-FHIR4 (2).zip](https://github.com/cqframework/cql-execution/files/15191257/CMS144FHIR-v1.3.000-FHIR4.2.zip)
[CMS144FHIR-v1.3.000-FHIR4-TestCases.zip](https://github.com/cqframework/cql-execution/files/15191260/CMS144FHIR-v1.3.000-FHIR4-TestCases.zip)

**Comment by hossenlopp** [comment]
Implemented in #320 and released with [v3.1.0](https://github.com/cqframework/cql-execution/releases/tag/v3.1.0).
