### ISSUE TITLE
Functions with the same name in CQL files.

### ISSUE THREAD

**Issue by sebaperez31** [cqframework/cql-execution#33]
Hi, I'm using the engine to run eCQMs. 
I've found a problem when there are different functions with the same name in the CQL file. This happens for instance in the FHIRHelpers.cql file (cql-exec-examples proyect). In these cases the engine is not able to find the correct function because it searches just by name, ignoring the parameters. I think it should be fixed in the file src\elm\reusable.coffee (FunctionRef class, exec function).
Thanks for writing the framework!. I look forward to hearing from you.  
Sebastian.

**Comment by cmoesel** [comment]
I'm way late in the response to this one (sorry) -- but we've added improved support for overloaded functions in CQL Execution 2.0.0 -- so now the execution engine will look at the arguments to find the best function match.

**Comment by JSRankins** [comment]
@cmoesel, is this resolution (of the overloaded functions) impacted by https://github.com/cqframework/clinical_quality_language/issues/442. I'm assuming not, since 442 is a rather old bug, but I wanted to make sure.

**Comment by cmoesel** [comment]
@JSRankins - I'll be honest with you... I'm not sure? If it's an issue, no one has noticed it yet.

**Comment by JSRankins** [comment]
Thanks @cmoesel. I was just reviewing the Translator tickets in conjunction with cql-execution to assess impact. We have not heard anything about this item either, but I thought you all would be more familiar with how function resolution was occurring within the engine.
