### ISSUE TITLE
cql-execution port to ES6...

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/cql-execution#47]
_From @turp1twin on November 17, 2016 4:47_

I have nothing against Coffeescript, but its future as a language has been debated as of late (due to ES6, ES7, babel, etc)... I have ported the cql-execution engine (and all tests) to ES6, which even with decaffeinate was more work than one might think! Not sure if you are interested, but I am willing to contribute it if you want it.. If not, no big deal, just thought I would offer it up... I currently have it in a private repo, but will open it up if there is any interest. Cheers!

Jeff

_Copied from original issue: cqframework/clinical_quality_language#80_

**Comment by brynrhodes** [comment]
_From @cmoesel on December 8, 2016 2:7_

Hi Jeff,

I think this sounds awesome.  After taking a long break from anything Javascript related, I've recently come back and found that I *really* like ES6 -- and some of the great tooling that's been built around ES6.  If I was writing cql-execution today, I'd certainly write it in ES6!

That said, we have a team that's already invested in the Coffeescript version (and is using Coffeescript elsewhere in their app).  They are a bit reluctant, at this point, to take on the risk of a full translation into ES6.  That may change, but that seems to be where things stand now.

But... I'd personally love to see your ES6 implementation.  Any chance you could grant me access so I could poke around and see how it works?

**Comment by brynrhodes** [comment]
_From @turp1twin on December 8, 2016 21:38_

Hey Chris,

Yeah, sounds good. I will give you access. It is still a work in progress, and there are a few bits that I still need to work out. That being said, I tried to stay as close to the structure you have in the coffee project, but might start to reorganize things a bit more... Anyways, have a play...

Jeff

**Comment by brynrhodes** [comment]
_From @seanknox on December 14, 2016 6:5_

Hey @turp1twin, the [Able Health team](https://github.com/AbleHealth) would love to participate if possible. Shoot me an email if you're interested: knoxville@ablehealth.com.

**Comment by brynrhodes** [comment]
_From @turp1twin on December 14, 2016 15:51_

Hey @seanknox, glad to get you involved. Will send you an email with some details...

Jeff

**Comment by brynrhodes** [comment]
_From @preston on February 8, 2017 16:51_

+1 to either ES6 or TypeScript-based canonical version. CoffeeScript was great while it lasted, but just isn't needed anymore.

**Comment by brynrhodes** [comment]
_From @preston on February 8, 2017 16:52_

@turp1twin Hi Jeff: any chance you may be able to make your version of the project available soon?

**Comment by brynrhodes** [comment]
_From @turp1twin on February 8, 2017 17:2_

Hey @preston I'll open it up later today. That being said, it needs some love, looking forward to contributions....

**Comment by brynrhodes** [comment]
_From @preston on February 8, 2017 17:15_

@turp1twin Right on... do you think it's in a functional enough state to be suitable for npm packaging/release as well?

For context, I'm a contributor to the [CQF Knartwork](https://github.com/cqframework/knartwork) project, and would love to be able to integrate these libraries either directly or through a web service interface.

**Comment by brynrhodes** [comment]
_From @turp1twin on February 8, 2017 17:19_

@preston The unit tests all run, but that is about all I have done with it so far. My day job has been keeping me crazy busy. The readme definitely needs updating for sure, before doing an NPM release....

**Comment by brynrhodes** [comment]
_From @turp1twin on February 8, 2017 17:22_

@preston The repository is public now...

**Comment by brynrhodes** [comment]
_From @rdingwell on February 8, 2017 19:53_

@preston as long as the port didn't change any of the api name spacing or method signatures you should be able to get started with the cql-execution npm package that is already published and built from the coffeescript version of the library.  

https://www.npmjs.com/package/cql-execution

**Comment by psbrandt** [comment]
Is this ticket being actively worked on? Has [decaffeinate](https://github.com/decaffeinate/decaffeinate) been considered?

**Comment by cmoesel** [comment]
Hi @psbrandt. I did some work on this about 6 months ago (see the [decaffeinate](https://github.com/cqframework/cql-execution/tree/decaffeinate) branch -- but it was interrupted midway through by a flurry of changes to the `master` (coffeescript) branch by a team that needed to implement enhancements/fixes ASAP.  A lot of really good changes were made there, and continued to be made as the CQL 1.3 specification evolved to its final state.

So... Now `master` has diverged quite a bit from the initial ES6 port and I'll likely end up starting the port from scratch, because, honestly, that will probably be easier than trying to decaffeinate and merge into the formerly decaffeinated branch.  I was just waiting for activity on master to settle down and stabilize a bit before picking it up again.  I think we're close!

**Comment by psbrandt** [comment]
Ah, sorry, I didn't see the branch. Plan sounds good 👍

**Comment by cmoesel** [comment]
NP.  Thanks for asking, and thanks for confirming that it's a feature wanted by others as well.

**Comment by awatson1978** [comment]
+1 for the need for an ES6 port.  This needs to be prioritized if CQL is to be adopted by the broader Node/React community.  Can we get this back on the radar and prioritized?

**Comment by cmoesel** [comment]
Hi @awatson1978 and @psbrandt  -- CQL Execution 2.0.0 was released at the end of last year and is a true JavaScript port.  Hopefully you already saw that, but if not, sorry for the late notice!
