### ISSUE TITLE
Certificate Error when running installDist

### ISSUE THREAD

**Issue by josephthomasvhp** [cqframework/cql-execution#81]
When I run (...\CQL\clinical_quality_language\Src\java>.\gradlew :cql-to-elm:installDist) I get a certificate error. Have you guys run into this issue before? If so, what did you do to fix it?
![certificate error](https://user-images.githubusercontent.com/36775503/53052360-2134e780-3464-11e9-87f4-9aa300941ab0.PNG)

**Comment by cmoesel** [comment]
It sounds like your JVM doesn't recognize the certificates being provided by repo1.maven.org or oss.sonatype.org.  I'm aware of two potential reasons for this:

1. The Java keystore really doesn't recognize those certificates (or their signing authorities)
2. You're behind a firewall the rewrites certificates (a somewhat common security practice for large corporations)

In either case, you probably need to import the certificates that the JVM fails to recognize (either the maven/sonatype certificates or your organization's certificates).  You might have a look at the following StackOverflow answer for a little more guidance:

https://stackoverflow.com/a/48593318

**Comment by josephthomasvhp** [comment]
You were spot on. I had the networking team here white list the oss and repo.maven URLs. Thank you for your help!
